#!/bin/bash
BROKER_IP=`grep broker_ip config.ini|awk '{print $3}'`
BROKER_PORT=`grep broker_port config.ini|awk '{print $3}'`
BROKER_TOPIC=`grep broker_topic config.ini|awk '{print $3}'|sed 's/#//g'`
while true;
	do
	let "level = $RANDOM%127+128"
	mosquitto_pub -h $BROKER_IP -p $BROKER_PORT -t ${BROKER_TOPIC}channel_b -m "$level"
	sleep 1
	let "level = $RANDOM%127+128"
	mosquitto_pub -h $BROKER_IP -p $BROKER_PORT -t ${BROKER_TOPIC}channel_a -m "$level"
	sleep 3
done
